FROM agrigorev/zoomcamp-model:2025

WORKDIR /code
COPY ./src/05-deployment/prediction_service_q6.py .
COPY ./pyproject.toml .

RUN pip install uv
RUN uv venv --system-site-packages
RUN uv sync

CMD ["uvicorn", "web_service:app", "--port", "8000"]