services:
  api:
    build:
      dockerfile: Dockerfile.api
      context: .

    container_name: zoomcamp-web-api
    ports:
      - "8000:8000"
#    environment:
#      - MODEL_PATH=/app/model/model.bin

